=== rachael27/VizCode/VizDesign_JuxtaposedH/iv03/treeml.dtd
<!--
	Copyright (c) 2003
	Jean-Daniel Fekete, INRIA
	Catherine Plaisant, University of Maryland

	$Id$

	DTD describing a tree structure for visualization

	Provided to support the InfoVis 2003 Contest
	See http://www.cs.umd.edu/hcil/iv03contest/index.shtml

-->

<!ELEMENT tree (declarations?, (branch | leaf)* )>
<!ATTLIST tree
  version CDATA #FIXED "1.0"
  src CDATA #IMPLIED
  desc CDATA #IMPLIED
  date CDATA #IMPLIED
  author CDATA #IMPLIED >

<!ELEMENT declarations (attributeDecl+) >
<!ELEMENT attributeDecl EMPTY>
<!ATTLIST attributeDecl
  name CDATA #REQUIRED
  type (Int|Integer|Long|Float|Real|String|Date|Category) "Int"
  control CDATA #IMPLIED >

<!ELEMENT branch ( attribute*, (branch | leaf)* ) >
<!ATTLIST branch
  label CDATA #IMPLIED >

<!ELEMENT leaf (attribute*) >
<!ATTLIST leaf
  label CDATA #IMPLIED >

<!ELEMENT attribute (#PCDATA) >
<!ATTLIST attribute
  name CDATA #REQUIRED
  value CDATA #REQUIRED >

=== rachael27/VizCode/VizDesign_JuxtaposedH/iv03/phylo_A_BAD1_IM__03-02-01.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE tree SYSTEM "treeml.dtd">
<tree>
 <declarations>
  <attributeDecl name="name" type="String"/>
  <attributeDecl name="length" type="Real"/>
 </declarations>
 <branch>
   <attribute name="name" value="?im57?"/>
  <branch>
    <attribute name="name" value="?im1?"/>
    <attribute name="length" value="0.21659"/>
   <branch>
     <attribute name="name" value="?im0?"/>
     <attribute name="length" value="0.00999"/>
    <leaf>
     <attribute name="name" value="SA0421"/>
     <attribute name="length" value="0.0"/></leaf>
    <leaf>
     <attribute name="name" value="SAV0463"/>
     <attribute name="length" value="0.0"/></leaf>
   </branch>
   <leaf>
    <attribute name="name" value="MW0417"/>
    <attribute name="length" value="-0.00539"/></leaf>
  </branch>
  <branch>
    <attribute name="name" value="?im56?"/>
    <attribute name="length" value="1.91648"/>
   <branch>
     <attribute name="name" value="?im22?"/>
     <attribute name="length" value="0.88104"/>
    <branch>
      <attribute name="name" value="?im20?"/>
      <attribute name="length" value="0.58663"/>
     <leaf>
      <attribute name="name" value="FN0659"/>
      <attribute name="length" value="2.17317"/></leaf>
     <branch>
       <attribute name="name" value="?im19?"/>
       <attribute name="length" value="0.81404"/>
      <branch>
        <attribute name="name" value="?im17?"/>
        <attribute name="length" value="0.16264"/>
       <branch>
         <attribute name="name" value="?im14?"/>
         <attribute name="length" value="0.38464"/>
        <branch>
         <attribute name="name" value="?im13?"/>
         <attribute name="length" value="0.62563"/>
         <branch>
         <attribute name="name" value="?im9?"/>
         <attribute name="length" value="1.91456"/>
         <branch>
         <attribute name="name" value="?im8?"/>
         <attribute name="length" value="0.43228"/>
         <branch>
         <attribute name="name" value="?im7?"/>
         <attribute name="length" value="0.82908"/>
         <branch>
         <attribute name="name" value="?im6?"/>
         <attribute name="length" value="1.3146"/>
         <branch>
         <attribute name="name" value="?im5?"/>
         <attribute name="length" value="2.94676"/>
         <branch>
         <attribute name="name" value="?im4?"/>
         <attribute name="length" value="0.05384"/>
         <leaf>
         <attribute name="name" value="ydcC"/>
         <attribute name="length" value="-0.09653"/></leaf>
         <branch>
         <attribute name="name" value="?im3?"/>
         <attribute name="length" value="1.45498"/>
         <branch>
         <attribute name="name" value="?im2?"/>
         <attribute name="length" value="0.19449"/>
         <leaf>
         <attribute name="name" value="spyM18_031"/>
         <attribute name="length" value="0.27183"/></leaf>
         <leaf>
         <attribute name="name" value="SP0152"/>
         <attribute name="length" value="0.07067"/></leaf>
         </branch>
         <leaf>
         <attribute name="name" value="spr0150"/>
         <attribute name="length" value="-0.18904"/></leaf>
         </branch>
         </branch>
         <leaf>
         <attribute name="name" value="ORF5"/>
         <attribute name="length" value="-0.05107"/></leaf>
         </branch>
         <leaf>
         <attribute name="name" value="yaeE_xa"/>
         <attribute name="length" value="-1.71905"/></leaf>
         </branch>
         <leaf>
         <attribute name="name" value="MW0791"/>
         <attribute name="length" value="-0.87214"/></leaf>
         </branch>
         <leaf>
         <attribute name="name" value="SA0770"/>
         <attribute name="length" value="-0.82437"/></leaf>
         </branch>
         <leaf>
         <attribute name="name" value="SAV0838"/>
         <attribute name="length" value="-0.43228"/></leaf>
         </branch>
         <branch>
         <attribute name="name" value="?im12?"/>
         <attribute name="length" value="0.30889"/>
         <branch>
         <attribute name="name" value="?im11?"/>
         <attribute name="length" value="1.49285"/>
         <branch>
         <attribute name="name" value="?im10?"/>
         <attribute name="length" value="0.73432"/>
         <leaf>
         <attribute name="name" value="atmE"/>
         <attribute name="length" value="2.4566"/></leaf>
         <leaf>
         <attribute name="name" value="yaeE_xc"/>
         <attribute name="length" value="2.5575"/></leaf>
         </branch>
         <leaf>
         <attribute name="name" value="PM1729"/>
         <attribute name="length" value="0.85743"/></leaf>
         </branch>
         <leaf>
         <attribute name="name" value="XF0874"/>
         <attribute name="length" value="2.28245"/></leaf>
         </branch>
        </branch>
        <leaf>
         <attribute name="name" value="BMEII0336"/>
         <attribute name="length" value="2.32444"/></leaf>
       </branch>
       <branch>
         <attribute name="name" value="?im16?"/>
         <attribute name="length" value="1.75874"/>
        <branch>
         <attribute name="name" value="?im15?"/>
         <attribute name="length" value="2.39385"/>
         <leaf>
         <attribute name="name" value="lmo2418"/>
         <attribute name="length" value="-0.01271"/></leaf>
         <leaf>
         <attribute name="name" value="lin2513"/>
         <attribute name="length" value="0.02691"/></leaf>
        </branch>
        <leaf>
         <attribute name="name" value="CC2668"/>
         <attribute name="length" value="-1.4087"/></leaf>
       </branch>
      </branch>
      <branch>
        <attribute name="name" value="?im18?"/>
        <attribute name="length" value="2.13834"/>
       <leaf>
        <attribute name="name" value="NMB1947"/>
        <attribute name="length" value="0.28208"/></leaf>
       <leaf>
        <attribute name="name" value="NMA0505"/>
        <attribute name="length" value="-0.24388"/></leaf>
      </branch>
     </branch>
    </branch>
    <branch>
      <attribute name="name" value="?im21?"/>
      <attribute name="length" value="2.6864"/>
     <leaf>
      <attribute name="name" value="aarA"/>
      <attribute name="length" value="-0.40355"/></leaf>
     <leaf>
      <attribute name="name" value="sfbC"/>
      <attribute name="length" value="1.59535"/></leaf>
    </branch>
   </branch>
   <branch>
     <attribute name="name" value="?im55?"/>
     <attribute name="length" value="1.08804"/>
    <branch>
      <attribute name="name" value="?im24?"/>
      <attribute name="length" value="0.66719"/>
     <leaf>
      <attribute name="name" value="HP1577"/>
      <attribute name="length" value="-0.03401"/></leaf>
     <branch>
       <attribute name="name" value="?im23?"/>
       <attribute name="length" value="0.03891"/>
      <leaf>
       <attribute name="name" value="jhp1485"/>
       <attribute name="length" value="-0.01657"/></leaf>
      <leaf>
       <attribute name="name" value="abcD"/>
       <attribute name="length" value="0.12047"/></leaf>
     </branch>
    </branch>
    <branch>
      <attribute name="name" value="?im54?"/>
      <attribute name="length" value="1.05544"/>
     <branch>
       <attribute name="name" value="?im34?"/>
       <attribute name="length" value="0.08757"/>
      <branch>
        <attribute name="name" value="?im32?"/>
        <attribute name="length" value="0.8494"/>
       <branch>
         <attribute name="name" value="?im28?"/>
         <attribute name="length" value="0.82377"/>
        <leaf>
         <attribute name="name" value="TP0119"/>
         <attribute name="length" value="0.2653"/></leaf>
        <branch>
         <attribute name="name" value="?im27?"/>
         <attribute name="length" value="0.32685"/>
         <branch>
         <attribute name="name" value="?im25?"/>
         <attribute name="length" value="0.23195"/>
         <leaf>
         <attribute name="name" value="BH3480"/>
         <attribute name="length" value="0.84082"/></leaf>
         <leaf>
         <attribute name="name" value="DR1357"/>
         <attribute name="length" value="0.26698"/></leaf>
         </branch>
         <branch>
         <attribute name="name" value="?im26?"/>
         <attribute name="length" value="0.17285"/>
         <leaf>
         <attribute name="name" value="AGR_L_763"/>
         <attribute name="length" value="0.0"/></leaf>
         <leaf>
         <attribute name="name" value="Atu4488"/>
         <attribute name="length" value="0.0"/></leaf>
         </branch>
        </branch>
       </branch>
       <branch>
         <attribute name="name" value="?im31?"/>
         <attribute name="length" value="1.93855"/>
        <branch>
         <attribute name="name" value="?im30?"/>
         <attribute name="length" value="0.45339"/>
         <branch>
         <attribute name="name" value="?im29?"/>
         <attribute name="length" value="0.21736"/>
         <leaf>
         <attribute name="name" value="yusB"/>
         <attribute name="length" value="0.51771"/></leaf>
         <leaf>
         <attribute name="name" value="BA_0756"/>
         <attribute name="length" value="0.58229"/></leaf>
         </branch>
         <leaf>
         <attribute name="name" value="YPO1319"/>
         <attribute name="length" value="0.37039"/></leaf>
        </branch>
        <leaf>
         <attribute name="name" value="Cgl0635"/>
         <attribute name="length" value="0.19331"/></leaf>
       </branch>
      </branch>
      <branch>
        <attribute name="name" value="?im33?"/>
        <attribute name="length" value="2.00936"/>
       <leaf>
        <attribute name="name" value="PA5504"/>
        <attribute name="length" value="0.62999"/></leaf>
       <leaf>
        <attribute name="name" value="VC0906"/>
        <attribute name="length" value="0.29451"/></leaf>
      </branch>
     </branch>
     <branch>
       <attribute name="name" value="?im53?"/>
